version: '3'

services:
  minecraft:
    build:
      context: .
      dockerfile: ./minecraft/Dockerfile
    image: minecraft
    container_name: minecraft
    ports:
      - 25565:25565
    expose:
      - 9100
    volumes:
      - "./minecraft/opt/minecraft/bin:/opt/minecraft/bin"
      - "./minecraft/opt/minecraft/data:/opt/minecraft/data"
      - "./minecraft/opt/grok_exporter/conf.d:/opt/grok_exporter/conf.d"
      - "./minecraft/opt/grok_exporter/patterns:/opt/grok_exporter/patterns"
      - "./minecraft/etc/supervisor/conf.d:/etc/supervisor/conf.d"
      - "./log/minecraft/minecraft:/var/log/minecraft"
      - "./log/minecraft/node_exporter:/var/log/node_exporter"
      - "./log/minecraft/grok_exporter:/var/log/grok_exporter"
      - "./log/minecraft/supervisor:/var/log/supervisor"
    environment:
      EULA: "true"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    expose:
      - 9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/var/lib/grafana:/var/lib/grafana"
